name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Create .env file
      run: echo $BOT_TOKEN > .env

    - name: Deploy to space
      run : |
            echo "$SPACE_TOKEN" | space login -t
            space dev
          

