name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
              echo ${{ secrets.BOT_TOKEN }} > .env
              ls -al

      - name: Install Space
        run: curl -fsSL https://deta.space/assets/space-cli.sh | sh

      - name: Deploy to Space
        run: |
             bash
             echo ${{ secrets.SPACE_TOKEN }} | /home/runner/.detaspace/bin/space login -t
             /home/runner/.detaspace/bin/space link -i ${{ secrets.PROJECT_ID }}
             /home/runner/.detaspace/bin/space push
            
          

